[tool.poetry]
name = "FNS Template app"
version = "0.0.5"
description = "Basic Demo of FNS app"
authors = ["etoplica <etoplica@paracloud.ai>"]
packages = [
	{ include = "app", from = "./"},
]
[[tool.poetry.source]]
name = "procaaso"
url = "https://pypi.procaas.us/simple/"
default = false
secondary = true


[tool.paracloud.definitions]
app = {main = "fns.py", type = "fns_task"}

[tool.poetry.dependencies]
python = "^3.8"
simple-pid = "^1.0.1"
procaaso-uns-sdk = "^0.3.3+7d54781b"
cpppo = "^4.4.2"
python-statemachine = "^0.8.0"
slackclient = "^2.9.4"
requests = "^2.28.1"
PyYAML = "^6.0"
debugpy = "^1.6.6"
pyrqlite = "^2.2.3"
uvicorn = "^0.23.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
