name: Recreation of Packaged App
on:
   pull_request:
    branches:
      - main
      - release/*

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::263704316862:role/IacCommonGithubActionsRole
          aws-region: us-west-2
          role-session-name: MySessionName
    
      - name: pull syndi package
         env:
          REGISTRY: 230177812114
          AWS_REGION: us-west-2
          IMAGE_TAG: latest
        run: |
          echo " 
          profiles:
            default:
              environment: stage.dev" > config

          docker pull ${{ env.REGISTRY }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/pc-syndi:${{ env.IMAGE_TAG }}
          docker run --rm -v $(pwd):/work -w /work ${{ env.REGISTRY }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/pc-syndi:${{ env.IMAGE_TAG }} package /work -c /work/config --output-dir /work

          rm -f config
      - name: delete fns-template.tgz
        run: rm -f fns-template.tgz

      - name: create a new file and rename it to fns-template.tgz
        run: |
          output=$(ls -t *.tar.gz 2>/dev/null | head -n 1)
          filename=$(printf "%s\n" "$output" | grep -oE '[^[:space:]]+\.tar\.gz' | tail -n 1)
          
          if [ -z "$filename" ]; then  echo "Could not find tar.gz filename in output"
            exit 1
          fi

          echo "Found file: $filename"

          mv $filename fns-template.tgz

      - name: commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add . 
          git commit -m "recreated packaged app"
          git push
